viloca:
  parental_dcv: resources/references/ref_majority_dcv.fasta
  parental_crpv: resources/references/pCrPV_3_parentalstock.fasta

vpipe_dcv:
  general:
      aligner: "bwa"

  input:
      reference: resources/references/ref_majority_dcv.fasta
      datadir: resources/samples/dcv_base
      read_length: 42
      samples_file: config/samples_dcv.tsv
      paired: true

  consensus_bcftools:
      max_coverage: 150000

  output:
      snv: false
      local: false
      global: false
      visualization: false
      diversity: false
      QA: false

vpipe_dcv_p0:
  general:
      aligner: "bwa"

  input:
      reference: /cluster/work/bewi/members/lfuhrmann/DCV-CrPV-cGAMP-primed-data-analysis/resources/references/dcv_eb.fasta
      datadir: resources/samples/dcv_base
      read_length: 42
      samples_file: config/samples_dcv_p0.tsv
      paired: true

  consensus_bcftools:
      max_coverage: 150000

  output:
      snv: false
      local: false
      global: false
      visualization: false
      diversity: false
      QA: false


vpipe_crpv_p0:
  general:
      aligner: "bwa"

  input:
      reference: /cluster/work/bewi/members/lfuhrmann/DCV-CrPV-cGAMP-primed-data-analysis/resources/references/crpv.fasta
      datadir: resources/samples/crpv_base
      read_length: 42
      samples_file: config/samples_crpv_p0.tsv
      paired: true

  consensus_bcftools:
      max_coverage: 150000

  output:
      snv: false
      local: false
      global: false
      visualization: false
      diversity: false
      QA: false

vpipe_crpv:
  general:
      aligner: "bwa"

  input:
      reference: resources/references/pCrPV_3_parentalstock.fasta
      datadir: resources/samples/crpv_base
      read_length: 42
      samples_file: config/samples_crpv.tsv
      paired: true

  consensus_bcftools:
      max_coverage: 150000

  output:
      snv: false
      local: false
      global: false
      visualization: false
      diversity: false
      QA: false
