vpipe:
  general:
      aligner: "bwa"

  input:
      reference: resources/references/dcv_eb.fasta
      datadir: resources/samples
      read_length: 42
      samples_file: config/samples.tsv
      paired: true

  consensus_bcftools:
      max_coverage: 150000

  output:
      datadir: results/results_vpipe

      snv: false
      local: false
      global: false
      visualization: false
      diversity: false
      QA: false

output_dir: results/
